'- Esse comando faz parte do módulo de coleta. Sua função é extrair nativamente algumas métricas do tráfego como:  tamanho médio, tamanho minimo  e máximo de pacotes.
 - Nessa versão do módulo de coleta, esse comando foi executado separadamento do deamon desenvolvido em python.

Funcionamento:
- É preciso ter a biblioteca tshark instalada
- É um comando dividido em duas pates, para cada dispositivo , a primeira parte captura as métricas dos pacotes com destino ao dispositivo e a outra parte captura as métricas dos pacotes com origem do dispositivo
- A saída do comando será um arquivo csv e cada linha será referente a analise de uma janela de tempo, no exemplo desses bloco, está sendo capturado todos os campos de uma classe comportamental inteira.
Parâmetros:
- arquivo pcap para extração dos dados
- tamanho da janela de tempo em segundos
- mac do dispositivo ao qual irá ser caluclado as métricas
- arquivo de saída 
'

tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==00:62:6e:51:27:2e",FRAMES,BYTES,"BYTES","AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon_Camera_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==00:62:6e:51:27:2e",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon_Camera_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==00:62:6e:51:27:2e",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon_Camera_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==e8:ab:fa:19:de:4f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon2_Camera_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==e8:ab:fa:19:de:4f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon2_Camera_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==e8:ab:fa:19:de:4f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Insteon2_Camera_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==44:65:0d:56:cc:d3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Amazon_Echo_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==44:65:0d:56:cc:d3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Amazon_Echo_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==44:65:0d:56:cc:d3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Amazon_Echo_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==e0:76:d0:33:bb:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >PixStart_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==e0:76:d0:33:bb:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >PixStart_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==e0:76:d0:33:bb:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >PixStart_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==d0:a6:37:df:a1:e1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Iphone_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==d0:a6:37:df:a1:e1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Iphone_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==d0:a6:37:df:a1:e1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Iphone_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==ac:bc:32:d4:6f:2f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBook_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==ac:bc:32:d4:6f:2f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBook_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==ac:bc:32:d4:6f:2f",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBook_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==74:c6:3b:29:d7:1d",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >iHome_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==74:c6:3b:29:d7:1d",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >iHome_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==74:c6:3b:29:d7:1d",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >iHome_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==ec:1a:59:79:f4:89",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BelkinWemoswitch_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==ec:1a:59:79:f4:89",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BelkinWemoswitch_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==ec:1a:59:79:f4:89",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BelkinWemoswitch_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==ec:1a:59:83:28:11",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Belkinmotionsensor_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==ec:1a:59:83:28:11",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Belkinmotionsensor_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==ec:1a:59:83:28:11",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Belkinmotionsensor_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==30:8c:fb:2f:e4:b2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==30:8c:fb:2f:e4:b2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==30:8c:fb:2f:e4:b2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==30:8c:fb:b6:ea:45",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam2_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==30:8c:fb:b6:ea:45",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam2_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==30:8c:fb:b6:ea:45",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Dropcam2_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==f4:5c:89:93:cc:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBookIphone_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==f4:5c:89:93:cc:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBookIphone_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==f4:5c:89:93:cc:85",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >MacBookIphone_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==70:5a:0f:e4:9b:c0",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >HPPrinter_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==70:5a:0f:e4:9b:c0",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >HPPrinter_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==70:5a:0f:e4:9b:c0",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >HPPrinter_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==b4:ce:f6:a7:a3:c2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==b4:ce:f6:a7:a3:c2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==b4:ce:f6:a7:a3:c2",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==18:b7:9e:02:20:44",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TribySpeaker_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==18:b7:9e:02:20:44",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TribySpeaker_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==18:b7:9e:02:20:44",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TribySpeaker_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==d0:73:d5:01:83:08",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >LiFXSmartBulb_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==d0:73:d5:01:83:08",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >LiFXSmartBulb_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==d0:73:d5:01:83:08",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >LiFXSmartBulb_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==18:b4:30:25:be:e4",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NESTsmokealarm_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==18:b4:30:25:be:e4",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NESTsmokealarm_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==18:b4:30:25:be:e4",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NESTsmokealarm_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==70:ee:50:03:b8:ac",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Netatmoweatherstation_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==70:ee:50:03:b8:ac",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Netatmoweatherstation_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==70:ee:50:03:b8:ac",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >Netatmoweatherstation_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==70:ee:50:18:34:43",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NetatmoWelcome_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==70:ee:50:18:34:43",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NetatmoWelcome_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==70:ee:50:18:34:43",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >NetatmoWelcome_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==d0:52:a8:00:67:5e",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SmartThings_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==d0:52:a8:00:67:5e",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SmartThings_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==d0:52:a8:00:67:5e",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SmartThings_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==74:6a:89:00:2e:25",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BlipcareBloodPressure_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==74:6a:89:00:2e:25",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BlipcareBloodPressure_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==74:6a:89:00:2e:25",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >BlipcareBloodPressure_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==08:21:ef:3b:fc:e3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungGalaxyTab_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==08:21:ef:3b:fc:e3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungGalaxyTab_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==08:21:ef:3b:fc:e3",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungGalaxyTab_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==00:16:6c:ab:6b:88",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungSmartCam_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==00:16:6c:ab:6b:88",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungSmartCam_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==00:16:6c:ab:6b:88",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >SamsungSmartCam_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==50:c7:bf:00:56:39",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkSmartplug_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==50:c7:bf:00:56:39",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkSmartplug_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==50:c7:bf:00:56:39",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkSmartplug_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==14:cc:20:51:33:ea",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkRouter_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==14:cc:20:51:33:ea",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkRouter_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==14:cc:20:51:33:ea",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TPLinkRouter_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==f4:f2:6d:93:51:f1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TP-LinkCloud_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==f4:f2:6d:93:51:f1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TP-LinkCloud_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==f4:f2:6d:93:51:f1",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >TP-LinkCloud_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==00:24:e4:11:18:a8",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsMonitor_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==00:24:e4:11:18:a8",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsMonitor_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==00:24:e4:11:18:a8",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsMonitor_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==00:24:e4:1b:6f:96",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsSmartscale_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==00:24:e4:1b:6f:96",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsSmartscale_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==00:24:e4:1b:6f:96",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsSmartscale_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==00:24:e4:20:28:c6",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsAurasmartLaptop_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==00:24:e4:20:28:c6",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsAurasmartLaptopunidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==00:24:e4:20:28:c6",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >WithingsAurasmartLaptop_unidirecional_dst.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.addr==74:2f:68:81:69:42",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone6_bidirecional.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.src==74:2f:68:81:69:42",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone6_unidirecional_src.csv;
tshark -r 16-10-01.pcap -qz io,stat,3600,"eth.dst==74:2f:68:81:69:42",FRAMES,BYTES,"AVG(frame.len)frame.len","MIN(frame.len)frame.len","MAX(frame.len)frame.len" -E header=y -E separator=, -E quote=d -E occurrence=f >AndroidPhone6_unidirecional_dst.csv;
